apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4414-go-helloworld-2:94f56dd7081f242ed1142b6575dd038b65953a83
          name: go-helloworld-2
